services:
  - type: web
    name: power-status-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python power_graph_render.py
    plan: free
    region: oregon
    runtime: python
