services:
  - type: web
    name: power-graph
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python power_graph_render.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
